baseURL = 'https://enpls.org/'
languageCode = 'fr-fr'
title = "EnPLS.org"
theme = "cyberretro"

[params]
    AuthorName = 'Maël G.'
    Description = 'System, Networking and other stuff'


[menu]
    [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
    [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2
    [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 3